In [3]:
pwd

u'/home/cognizac/PycharmProjects/BIA-660-C-Spring2017/Video_Lectures/004-MyPandas'

In [7]:
infile = open('SalesJan2009.csv')

In [8]:
lines = infile.readlines()

In [11]:
lines = lines[0].split('\r')

In [14]:
lines[:5]

['Transaction_date,Product,Price,Payment_Type,Name,City,State,Country,Account_Created,Last_Login,Latitude,Longitude',
 '1/2/09 6:17,Product1,1200,Mastercard,carolina,Basildon,England,United Kingdom,1/2/09 6:00,1/2/09 6:08,51.5,-1.1166667',
 '1/2/09 4:53,Product1,1200,Visa,Betina,Parkville                   ,MO,United States,1/2/09 4:42,1/2/09 7:49,39.195,-94.68194',
 '1/2/09 13:08,Product1,1200,Mastercard,Federica e Andrea,Astoria                     ,OR,United States,1/1/09 16:21,1/3/09 12:32,46.18806,-123.83',
 '1/3/09 14:44,Product1,1200,Visa,Gouya,Echuca,Victoria,Australia,9/25/05 21:13,1/3/09 14:22,-36.1333333,144.75']

In [15]:
data = [l.split(',') for l in lines]

In [17]:
header = data[0]

In [18]:
len(data[0])

12

In [19]:
[len(row) == 12 for row in data]

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [39]:
[(index, row) for index, row in enumerate(data) if len(row) != 12]

[]

In [36]:
things = lines[559].split('"')
len(things[0].split(',')[:-1] + [things[1]] + things[-1].split(',')[1:])

12

In [37]:
data[559] = things[0].split(',')[:-1] + [things[1]] + things[-1].split(',')[1:]

[['Transaction_date',
  'Product',
  'Price',
  'Payment_Type',
  'Name',
  'City',
  'State',
  'Country',
  'Account_Created',
  'Last_Login',
  'Latitude',
  'Longitude'],
 ['1/2/09 6:17',
  'Product1',
  '1200',
  'Mastercard',
  'carolina',
  'Basildon',
  'England',
  'United Kingdom',
  '1/2/09 6:00',
  '1/2/09 6:08',
  '51.5',
  '-1.1166667'],
 ['1/2/09 4:53',
  'Product1',
  '1200',
  'Visa',
  'Betina',
  'Parkville                   ',
  'MO',
  'United States',
  '1/2/09 4:42',
  '1/2/09 7:49',
  '39.195',
  '-94.68194'],
 ['1/2/09 13:08',
  'Product1',
  '1200',
  'Mastercard',
  'Federica e Andrea',
  'Astoria                     ',
  'OR',
  'United States',
  '1/1/09 16:21',
  '1/3/09 12:32',
  '46.18806',
  '-123.83'],
 ['1/3/09 14:44',
  'Product1',
  '1200',
  'Visa',
  'Gouya',
  'Echuca',
  'Victoria',
  'Australia',
  '9/25/05 21:13',
  '1/3/09 14:22',
  '-36.1333333',
  '144.75'],
 ['1/4/09 12:56',
  'Product2',
  '3600',
  'Visa',
  'Gerd W ',
  'Cahaba Heights              ',
  'AL',
  'United States',
  '11/15/08 15:47',
  '1/4/09 12:45',
  '33.52056',
  '-86.8025'],
 ['1/4/09 13:19',
  'Product1',
  '1200',
  'Visa',
  'LAURENCE',
  'Mickleton                   ',
  'NJ',
  'United States',
  '9/24/08 15:19',
  '1/4/09 13:04',
  '39.79',
  '-75.23806'],
 ['1/4/09 20:11',
  'Product1',
  '1200',
  'Mastercard',
  'Fleur',
  'Peoria                      ',
  'IL',
  'United States',
  '1/3/09 9:38',
  '1/4/09 19:45',
  '40.69361',
  '-89.58889'],
 ['1/2/09 20:09',
  'Product1',
  '1200',
  'Mastercard',
  'adam',
  'Martin                      ',
  'TN',
  'United States',
  '1/2/09 17:43',
  '1/4/09 20:01',
  '36.34333',
  '-88.85028'],
 ['1/4/09 13:17',
  'Product1',
  '1200',
  'Mastercard',
  'Renee Elisabeth',
  'Tel Aviv',
  'Tel Aviv',
  'Israel',
  '1/4/09 13:03',
  '1/4/09 22:10',
  '32.0666667',
  '34.7666667'],
 ['1/4/09 14:11',
  'Product1',
  '1200',
  'Visa',
  'Aidan',
  'Chatou',
  'Ile-de-France',
  'France',
  '6/3/08 4:22',
  '1/5/09 1:17',
  '48.8833333',
  '2.15'],
 ['1/5/09 2:42',
  'Product1',
  '1200',
  'Diners',
  'Stacy',
  'New York                    ',
  'NY',
  'United States',
  '1/5/09 2:23',
  '1/5/09 4:59',
  '40.71417',
  '-74.00639'],
 ['1/5/09 5:39',
  'Product1',
  '1200',
  'Amex',
  'Heidi',
  'Eindhoven',
  'Noord-Brabant',
  'Netherlands',
  '1/5/09 4:55',
  '1/5/09 8:15',
  '51.45',
  '5.4666667'],
 ['1/2/09 9:16',
  'Product1',
  '1200',
  'Mastercard',
  'Sean ',
  'Shavano Park                ',
  'TX',
  'United States',
  '1/2/09 8:32',
  '1/5/09 9:05',
  '29.42389',
  '-98.49333'],
 ['1/5/09 10:08',
  'Product1',
  '1200',
  'Visa',
  'Georgia',
  'Eagle                       ',
  'ID',
  'United States',
  '11/11/08 15:53',
  '1/5/09 10:05',
  '43.69556',
  '-116.35306'],
 ['1/2/09 14:18',
  'Product1',
  '1200',
  'Visa',
  'Richard',
  'Riverside                   ',
  'NJ',
  'United States',
  '12/9/08 12:07',
  '1/5/09 11:01',
  '40.03222',
  '-74.95778'],
 ['1/4/09 1:05',
  'Product1',
  '1200',
  'Diners',
  'Leanne',
  'Julianstown',
  'Meath',
  'Ireland',
  '1/4/09 0:00',
  '1/5/09 13:36',
  '53.6772222',
  '-6.3191667'],
 ['1/5/09 11:37',
  'Product1',
  '1200',
  'Visa',
  'Janet',
  'Ottawa',
  'Ontario',
  'Canada',
  '1/5/09 9:35',
  '1/5/09 19:24',
  '45.4166667',
  '-75.7'],
 ['1/6/09 5:02',
  'Product1',
  '1200',
  'Diners',
  'barbara',
  'Hyderabad',
  'Andhra Pradesh',
  'India',
  '1/6/09 2:41',
  '1/6/09 7:52',
  '17.3833333',
  '78.4666667'],
 ['1/6/09 7:45',
  'Product2',
  '3600',
  'Visa',
  'Sabine',
  'London',
  'England',
  'United Kingdom',
  '1/6/09 7:00',
  '1/6/09 9:17',
  '51.52721',
  '0.14559'],
 ['1/2/09 7:35',
  'Product1',
  '1200',
  'Diners',
  'Hani',
  'Salt Lake City              ',
  'UT',
  'United States',
  '12/30/08 5:44',
  '1/6/09 10:52',
  '40.76083',
  '-111.89028'],
 ['1/6/09 12:56',
  'Product1',
  '1200',
  'Visa',
  'Jeremy',
  'Manchester',
  'England',
  'United Kingdom',
  '1/6/09 10:58',
  '1/6/09 13:31',
  '53.5',
  '-2.2166667'],
 ['1/1/09 11:05',
  'Product1',
  '1200',
  'Diners',
  'Janis',
  'Ballynora',
  'Cork',
  'Ireland',
  '12/10/07 12:37',
  '1/7/09 1:52',
  '51.8630556',
  '-8.58'],
 ['1/5/09 4:10',
  'Product1',
  '1200',
  'Mastercard',
  'Nicola',
  'Roodepoort',
  'Gauteng',
  'South Africa',
  '1/5/09 2:33',
  '1/7/09 5:13',
  '-26.1666667',
  '27.8666667'],
 ['1/6/09 7:18',
  'Product1',
  '1200',
  'Visa',
  'asuman',
  'Chula Vista                 ',
  'CA',
  'United States',
  '1/6/09 7:07',
  '1/7/09 7:08',
  '32.64',
  '-117.08333'],
 ['1/2/09 1:11',
  'Product1',
  '1200',
  'Mastercard',
  'Lena',
  'Kuopio',
  'Ita-Suomen Laani',
  'Finland',
  '12/31/08 2:48',
  '1/7/09 10:20',
  '62.9',
  '27.6833333'],
 ['1/1/09 2:24',
  'Product1',
  '1200',
  'Visa',
  'Lisa',
  'Sugar Land                  ',
  'TX',
  'United States',
  '1/1/09 1:56',
  '1/7/09 10:52',
  '29.61944',
  '-95.63472'],
 ['1/7/09 8:08',
  'Product1',
  '1200',
  'Diners',
  'Bryan Kerrene',
  'New York                    ',
  'NY',
  'United States',
  '1/7/09 7:39',
  '1/7/09 12:38',
  '40.71417',
  '-74.00639'],
 ['1/2/09 2:57',
  'Product1',
  '1200',
  'Visa',
  'chris',
  'London',
  'England',
  'United Kingdom',
  '1/3/08 7:23',
  '1/7/09 13:14',
  '51.52721',
  '0.14559'],
 ['1/1/09 20:21',
  'Product1',
  '1200',
  'Visa',
  'Maxine',
  'Morton                      ',
  'IL',
  'United States',
  '10/24/08 6:48',
  '1/7/09 20:49',
  '40.61278',
  '-89.45917'],
 ['1/8/09 0:42',
  'Product1',
  '1200',
  'Visa',
  'Family',
  'Los Gatos                   ',
  'CA',
  'United States',
  '1/8/09 0:28',
  '1/8/09 3:39',
  '37.22667',
  '-121.97361'],
 ['1/8/09 3:56',
  'Product1',
  '1200',
  'Mastercard',
  'Katherine',
  'New York                    ',
  'NY',
  'United States',
  '1/8/09 3:33',
  '1/8/09 6:19',
  '40.71417',
  '-74.00639'],
 ['1/8/09 3:16',
  'Product1',
  '1200',
  'Mastercard',
  'Linda',
  'Miami                       ',
  'FL',
  'United States',
  '1/8/09 3:06',
  '1/8/09 6:34',
  '25.77389',
  '-80.19389'],
 ['1/8/09 1:59',
  'Product1',
  '1200',
  'Mastercard',
  'SYLVIA',
  'Vesenaz',
  'Geneve',
  'Switzerland',
  '11/28/07 11:56',
  '1/8/09 7:20',
  '46.2333333',
  '6.2'],
 ['1/3/09 9:03',
  'Product1',
  '1200',
  'Diners',
  'Sheila',
  'Brooklyn                    ',
  'NY',
  'United States',
  '1/3/09 8:47',
  '1/8/09 10:38',
  '40.65',
  '-73.95'],
 ['1/5/09 13:17',
  'Product1',
  '1200',
  'Mastercard',
  'Stephanie',
  'Badhoevedorp',
  'Noord-Holland',
  'Netherlands',
  '1/5/09 12:45',
  '1/8/09 11:45',
  '52.3333333',
  '4.7833333'],
 ['1/6/09 7:46',
  'Product1',
  '1200',
  'Amex',
  'Kelly',
  'Reston                      ',
  'VA',
  'United States',
  '1/6/09 7:30',
  '1/8/09 12:40',
  '38.96861',
  '-77.34139'],
 ['1/5/09 20:00',
  'Product2',
  '3600',
  'Visa',
  'James',
  'Burpengary',
  'Queensland',
  'Australia',
  '12/10/08 19:53',
  '1/8/09 17:58',
  '-27.1666667',
  '152.95'],
 ['1/8/09 16:24',
  'Product1',
  '1200',
  'Visa',
  'jennifer',
  'Phoenix                     ',
  'AZ',
  'United States',
  '1/8/09 15:57',
  '1/8/09 18:30',
  '33.44833',
  '-112.07333'],
 ['1/9/09 6:39',
  'Product1',
  '1200',
  'Mastercard',
  'Anneli',
  'Houston                     ',
  'TX',
  'United States',
  '1/9/09 5:09',
  '1/9/09 7:11',
  '29.76306',
  '-95.36306'],
 ['1/6/09 22:19',
  'Product2',
  '3600',
  'Amex',
  'Ritz',
  'Pittsfield                  ',
  'VT',
  'United States',
  '1/6/09 12:00',
  '1/9/09 10:05',
  '43.77222',
  '-72.81333'],
 ['1/6/09 23:00',
  'Product2',
  '3600',
  'Amex',
  'Sylvia',
  'Pittsfield                  ',
  'VT',
  'United States',
  '1/6/09 12:00',
  '1/9/09 10:05',
  '43.77222',
  '-72.81333'],
 ['1/7/09 7:44',
  'Product1',
  '1200',
  'Mastercard',
  'Marie',
  'Ball Ground                 ',
  'GA',
  'United States',
  '1/7/09 5:35',
  '1/9/09 10:52',
  '34.33806',
  '-84.37667'],
 ['1/3/09 13:24',
  'Product1',
  '1200',
  'Visa',
  'Mehmet Fatih',
  'Helsingor',
  'Frederiksborg',
  'Denmark',
  '1/3/09 12:47',
  '1/9/09 11:14',
  '56.0333333',
  '12.6166667'],
 ['1/7/09 15:12',
  'Product2',
  '3600',
  'Visa',
  'Anabela',
  'Flossmoor                   ',
  'IL',
  'United States',
  '1/5/09 19:55',
  '1/9/09 16:03',
  '41.54278',
  '-87.68472'],
 ['1/7/09 20:15',
  'Product1',
  '1200',
  'Amex',
  'Nicole',
  'Houston                     ',
  'TX',
  'United States',
  '1/7/09 17:17',
  '1/9/09 20:02',
  '29.76306',
  '-95.36306'],
 ['1/3/09 10:11',
  'Product2',
  '3600',
  'Visa',
  'Christiane ',
  'Delray Beach                ',
  'FL',
  'United States',
  '1/3/09 9:27',
  '1/10/09 9:46',
  '26.46111',
  '-80.07306'],
 ['1/9/09 15:58',
  'Product1',
  '1200',
  'Mastercard',
  'Sari',
  'Newbury',
  'England',
  'United Kingdom',
  '1/9/09 14:53',
  '1/10/09 13:16',
  '51.4',
  '-1.3166667'],
 ['1/3/09 13:11',
  'Product1',
  '1200',
  'Mastercard',
  'simone',
  'Kobenhavn',
  'Kobenhavn',
  'Denmark',
  '10/31/08 0:31',
  '1/10/09 13:24',
  '55.6666667',
  '12.5833333'],
 ['1/10/09 12:57',
  'Product1',
  '1200',
  'Amex',
  'Vanessa',
  'Sandy Springs               ',
  'GA',
  'United States',
  '2/7/07 20:16',
  '1/10/09 14:09',
  '33.92417',
  '-84.37861'],
 ['1/10/09 14:43',
  'Product1',
  '1200',
  'Diners',
  'Anupam',
  'Kinsaley',
  'Dublin',
  'Ireland',
  '1/9/09 11:38',
  '1/10/09 14:37',
  '53.4247222',
  '-6.1758333'],
 ['1/10/09 12:05',
  'Product1',
  '1200',
  'Visa',
  'Karina',
  'Fort Lauderdale             ',
  'FL',
  'United States',
  '7/1/08 12:53',
  '1/10/09 16:33',
  '26.12194',
  '-80.14361'],
 ['1/6/09 1:20',
  'Product1',
  '1200',
  'Mastercard',
  'Frank',
  'Melbourne',
  'Victoria',
  'Australia',
  '1/2/09 17:51',
  '1/10/09 18:27',
  '-37.8166667',
  '144.9666667'],
 ['1/10/09 14:56',
  'Product1',
  '1200',
  'Visa',
  'Angela',
  'Ankeny                      ',
  'IA',
  'United States',
  '1/8/09 3:06',
  '1/10/09 19:41',
  '41.72972',
  '-93.60556'],
 ['1/7/09 10:01',
  'Product1',
  '1200',
  'Visa',
  'Darren',
  'Pittsboro                   ',
  'NC',
  'United States',
  '1/7/09 9:04',
  '1/10/09 20:02',
  '35.72',
  '-79.1775'],
 ['1/1/09 1:26',
  'Product1',
  '1200',
  'Mastercard',
  'Nikki',
  'New Rochelle                ',
  'NY',
  'United States',
  '1/1/09 0:58',
  '1/10/09 21:31',
  '40.91139',
  '-73.78278'],
 ['1/11/09 2:04',
  'Product1',
  '1200',
  'Visa',
  'chris',
  'Gold Coast',
  'Queensland',
  'Australia',
  '1/11/09 0:33',
  '1/11/09 2:11',
  '-28',
  '153.4333333'],
 ['1/11/09 14:17',
  'Product1',
  '1200',
  'Visa',
  'Stephanie',
  'Brussels',
  'Brussels (Bruxelles)',
  'Belgium',
  '1/11/09 13:39',
  '1/11/09 13:39',
  '50.8333333',
  '4.3333333'],
 ['1/10/09 21:38',
  'Product1',
  '1200',
  'Visa',
  'Anushka',
  'Maple Ridge District Municipality',
  'British Columbia',
  'Canada',
  '1/10/09 21:17',
  '1/11/09 19:32',
  '49.25',
  '-122.5'],
 ['1/7/09 6:18',
  'Product1',
  '1200',
  'Mastercard',
  'June ',
  'Beachwood                   ',
  'OH',
  'United States',
  '2/23/06 11:56',
  '1/11/09 19:35',
  '41.46444',
  '-81.50889'],
 ['1/4/09 8:39',
  'Product2',
  '3600',
  'Diners',
  'Baybars',
  'Prince Albert',
  'Saskatchewan',
  'Canada',
  '1/3/09 17:17',
  '1/11/09 21:05',
  '53.2',
  '-105.75'],
 ['1/5/09 0:31',
  'Product1',
  '1200',
  'Mastercard',
  'Bonnie',
  'Saltsjobaden',
  'Stockholm',
  'Sweden',
  '1/4/09 23:45',
  '1/12/09 0:37',
  '59.2833333',
  '18.3'],
 ['1/2/09 6:07',
  'Product1',
  '1200',
  'Visa',
  'Cindy ',
  'Kemble',
  'England',
  'United Kingdom',
  '12/30/08 10:21',
  '1/12/09 2:24',
  '51.6766667',
  '-2.0180556'],
 ['1/12/09 3:25',
  'Product1',
  '1200',
  'Mastercard',
  'chrissy',
  'W Lebanon                   ',
  'NH',
  'United States',
  '1/12/09 3:12',
  '1/12/09 3:22',
  '43.64917',
  '-72.31083'],
 ['1/4/09 13:56',
  'Product1',
  '1200',
  'Mastercard',
  'Tamar',
  'Headley',
  'England',
  'United Kingdom',
  '11/29/07 9:23',
  '1/12/09 5:38',
  '51.1166667',
  '-0.8166667'],
 ['1/7/09 0:12',
  'Product2',
  '3600',
  'Mastercard',
  'Deirdre',
  'Lausanne',
  'Vaud',
  'Switzerland',
  '12/1/08 6:25',
  '1/12/09 6:55',
  '46.5333333',
  '6.6666667'],
 ['1/12/09 5:18',
  'Product1',
  '1200',
  'Mastercard',
  'Bernadett',
  'Southampton',
  'England',
  'United Kingdom',
  '1/12/09 4:45',
  '1/12/09 8:08',
  '50.9',
  '-1.4'],
 ['1/8/09 15:16',
  'Product1',
  '1200',
  'Visa',
  'Dottie',
  'Woodsboro                   ',
  'MD',
  'United States',
  '1/8/09 14:56',
  '1/12/09 9:29',
  '39.53306',
  '-77.315'],
 ['1/11/09 11:33',
  'Product1',
  '1200',
  'Visa',
  'Stefan',
  'Stavanger',
  'Rogaland',
  'Norway',
  '1/11/09 9:02',
  '1/12/09 10:37',
  '58.9666667',
  '5.75'],
 ['1/7/09 20:22',
  'Product1',
  '1200',
  'Visa',
  'Gina',
  'Red Deer',
  'Alberta',
  'Canada',
  '11/23/08 19:30',
  '1/12/09 12:24',
  '52.2666667',
  '-113.8'],
 ['1/2/09 22:00',
  'Product1',
  '1200',
  'Diners',
  'Lynne',
  'Memphis                     ',
  'TN',
  'United States',
  '1/2/09 21:04',
  '1/12/09 13:18',
  '35.14944',
  '-90.04889'],
 ['1/5/09 13:52',
  'Product1',
  '1200',
  'Mastercard',
  'Tammy',
  'Morges',
  'Vaud',
  'Switzerland',
  '1/5/09 5:55',
  '1/12/09 14:04',
  '46.5166667',
  '6.5'],
 ['1/8/09 20:32',
  'Product1',
  '1200',
  'Visa',
  'Kim',
  'Calgary',
  'Alberta',
  'Canada',
  '1/8/09 20:21',
  '1/12/09 14:07',
  '51.0833333',
  '-114.0833333'],
 ['1/8/09 13:34',
  'Product1',
  '1200',
  'Visa',
  'Bruce',
  'Belleville',
  'Ontario',
  'Canada',
  '1/6/09 14:38',
  '1/12/09 18:31',
  '44.1666667',
  '-77.3833333'],
 ['1/11/09 13:08',
  'Product1',
  '1200',
  'Visa',
  'Rosa Maria',
  'Cincinnati                  ',
  'OH',
  'United States',
  '1/11/09 12:38',
  '1/12/09 18:44',
  '39.16194',
  '-84.45694'],
 ['1/12/09 19:04',
  'Product1',
  '1200',
  'Visa',
  'Lydia',
  'Comox',
  'British Columbia',
  'Canada',
  '9/20/08 20:53',
  '1/12/09 19:01',
  '49.6833333',
  '-124.9333333'],
 ['1/12/09 13:41',
  'Product1',
  '1200',
  'Visa',
  'Eric',
  'Gasperich',
  'Luxembourg',
  'Luxembourg',
  '1/12/09 13:16',
  '1/13/09 1:03',
  '49.5855556',
  '6.1230556'],
 ['1/11/09 10:38',
  'Product1',
  '1200',
  'Mastercard',
  'AnaPaula',
  'Helens Bay',
  'Northern Ireland',
  'United Kingdom',
  '9/4/08 9:26',
  '1/13/09 2:36',
  '54.65',
  '-5.7333333'],
 ['1/13/09 5:57',
  'Product1',
  '1200',
  'Visa',
  'Robin',
  'Milan',
  'Lombardy',
  'Italy',
  '10/15/08 5:31',
  '1/13/09 5:55',
  '45.4666667',
  '9.2'],
 ['1/13/09 6:13',
  'Product1',
  '1200',
  'Visa',
  'Gitte',
  'Staten Island               ',
  'NY',
  'United States',
  '1/13/09 5:17',
  '1/13/09 7:33',
  '40.63667',
  '-74.15917'],
 ['1/8/09 13:14',
  'Product1',
  '1200',
  'Visa',
  'Dr. Claudia',
  'Oslo',
  'Oslo',
  'Norway',
  '1/8/09 12:47',
  '1/13/09 10:49',
  '59.9166667',
  '10.75'],
 ['1/2/09 11:41',
  'Product1',
  '1200',
  'Visa',
  'Crystal',
  'Farmington',
  'Michigan',
  'United States',
  '1/1/09 12:00',
  '1/13/09 18:34',
  '42.46444',
  '-83.37639'],
 ['1/7/09 19:50',
  'Product1',
  '1200',
  'Diners',
  'Delphine',
  'Santa Monica                ',
  'CA',
  'United States',
  '1/3/09 12:04',
  '1/13/09 20:17',
  '34.01944',
  '-118.49028'],
 ['1/1/09 20:28',
  'Product1',
  '1200',
  'Visa',
  'nathalie',
  'Calgary',
  'Alberta',
  'Canada',
  '1/1/09 20:11',
  '1/13/09 21:11',
  '51.0833333',
  '-114.0833333'],
 ['1/3/09 15:22',
  'Product1',
  '1200',
  'Mastercard',
  'Lindi',
  'Vancouver',
  'British Columbia',
  'Canada',
  '2/20/08 22:45',
  '1/13/09 23:02',
  '49.25',
  '-123.1333333'],
 ['1/12/09 3:03',
  'Product2',
  '3600',
  'Mastercard',
  'Valda',
  'Irvine                      ',
  'CA',
  'United States',
  '1/12/09 2:48',
  '1/14/09 1:07',
  '33.66944',
  '-117.82222'],
 ['1/5/09 8:58',
  'Product2',
  '3600',
  'Mastercard',
  'Marcia',
  'Telgte',
  'Nordrhein-Westfalen',
  'Germany',
  '9/1/08 3:39',
  '1/14/09 2:07',
  '52.3333333',
  '7.9'],
 ['1/10/09 14:03',
  'Product1',
  '1200',
  'Mastercard',
  'Kevin',
  'Cheltenham',
  'England',
  'United Kingdom',
  '3/13/06 4:56',
  '1/14/09 2:22',
  '51.9',
  '-2.0833333'],
 ['1/13/09 11:26',
  'Product1',
  '1200',
  'Visa',
  'Clare',
  'Keller                      ',
  'VA',
  'United States',
  '1/13/09 11:15',
  '1/14/09 2:39',
  '37.61917',
  '-75.76417'],
 ['1/2/09 12:18',
  'Product1',
  '1200',
  'Visa',
  'Alice',
  'Nakskov',
  'Storstrom',
  'Denmark',
  '12/5/07 11:37',
  '1/14/09 4:05',
  '54.8333333',
  '11.15'],
 ['1/14/09 4:54',
  'Product1',
  '1200',
  'Mastercard',
  'ZENA',
  'Honolulu                    ',
  'HI',
  'United States',
  '1/14/09 4:34',
  '1/14/09 4:43',
  '21.30694',
  '-157.85833'],
 ['1/6/09 17:15',
  'Product1',
  '1200',
  'Visa',
  'Andrea',
  'Bubuieci',
  'Chisinau',
  'Moldova',
  '12/24/08 17:31',
  '1/14/09 10:27',
  '46.985',
  '28.9425'],
 ['1/3/09 13:56',
  'Product1',
  '1200',
  'Visa',
  'Rennae',
  'Amelia Island               ',
  'FL',
  'United States',
  '1/3/09 12:30',
  '1/14/09 13:03',
  '30.66944',
  '-81.46278'],
 ['1/4/09 7:54',
  'Product1',
  '1200',
  'Visa',
  'Gerhard',
  'Alliston',
  'Ontario',
  'Canada',
  '10/21/05 21:49',
  '1/14/09 13:06',
  '44.15',
  '-79.8666667'],
 ['1/12/09 7:28',
  'Product1',
  '1200',
  'Amex',
  'Megan',
  'La Alberca',
  'Murcia',
  'Spain',
  '12/10/08 16:41',
  '1/14/09 13:44',
  '37.9333333',
  '-1.1333333'],
 ['1/6/09 15:15',
  'Product1',
  '1200',
  'Mastercard',
  'Danielle',
  'Rathgar',
  'Dublin',
  'Ireland',
  '1/6/09 14:59',
  '1/14/09 14:33',
  '53.3122222',
  '-6.2683333'],
 ['1/13/09 23:56',
  'Product1',
  '1200',
  'Mastercard',
  'Tod',
  'Coral Gables                ',
  'FL',
  'United States',
  '1/13/09 23:13',
  '1/14/09 15:17',
  '25.72111',
  '-80.26861'],
 ['1/14/09 19:32',
  'Product1',
  '1200',
  'Visa',
  'Janaina',
  'Miami                       ',
  'FL',
  'United States',
  '12/16/08 22:19',
  '1/14/09 19:28',
  '25.77389',
  '-80.19389'],
 ['1/6/09 21:13',
  'Product1',
  '1200',
  'Visa',
  'Kofi',
  'Vancouver',
  'British Columbia',
  'Canada',
  '1/7/08 21:16',
  '1/14/09 20:50',
  '49.25',
  '-123.1333333'],
 ['1/14/09 11:19',
  'Product1',
  '1200',
  'Visa',
  'Jennifer',
  'Jumeira',
  'Dubayy',
  'United Arab Emirates',
  '1/14/09 10:44',
  '1/14/09 21:26',
  '25.2097222',
  '55.2477778'],
 ['1/13/09 19:39',
  'Product1',
  '1200',
  'Visa',
  'Jolene ',
  'Englewood                   ',
  'CO',
  'United States',
  '1/6/09 22:00',
  '1/14/09 22:02',
  '39.64778',
  '-104.98722'],
 ['1/8/09 7:26',
  'Product1',
  '1200',
  'Mastercard',
  'anne',
  'Bournemouth',
  'England',
  'United Kingdom',
  '1/25/08 15:46',
  '1/15/09 1:36',
  '50.7166667',
  '-1.8833333'],
 ['1/15/09 2:40',
  'Product1',
  '1200',
  'Mastercard',
  'Alexis',
  'Genoa                       ',
  'IL',
  'United States',
  '1/15/09 2:04',
  '1/15/09 2:04',
  '42.09722',
  '-88.69278'],
 ['1/12/09 6:40',
  'Product1',
  '1200',
  'Visa',
  'Dez',
  "Al 'Adliyah",
  'Al Manamah',
  'Bahrain',
  '1/10/09 12:50',
  '1/15/09 4:46',
  '26.2172222',
  '50.5405556'],
 ['1/15/09 3:43',
  'Product1',
  '1200',
  'Visa',
  'Stephanie',
  'Rouen',
  'Upper Normandy',
  'France',
  '12/26/08 9:01',
  '1/15/09 5:39',
  '49.4333333',
  '1.0833333'],
 ['1/5/09 15:39',
  'Product1',
  '1200',
  'Visa',
  'Melissa ',
  'Parkland                    ',
  'FL',
  'United States',
  '12/10/08 9:14',
  '1/15/09 6:01',
  '26.30972',
  '-80.2375'],
 ['1/10/09 5:21',
  'Product1',
  '1200',
  'Amex',
  'CLARE',
  'San Francisco               ',
  'CA',
  'United States',
  '1/10/09 0:07',
  '1/15/09 6:25',
  '37.775',
  '-122.41833'],
 ['1/15/09 4:12',
  'Product1',
  '1200',
  'Mastercard',
  'catherine',
  'Keller                      ',
  'VA',
  'United States',
  '1/15/09 4:02',
  '1/15/09 6:59',
  '37.61917',
  '-75.76417'],
 ['1/12/09 11:48',